# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#   Samsung proprietary binaries and libraries for trebon


#  This file is generated by device/samsung/trebon/extract-files.sh



# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/samsung/trebon/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/samsung/trebon/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so \
    vendor/samsung/trebon/proprietary/lib/libsecril-client.so:obj/lib/libsecril-client.so

# HW libs
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/samsung/trebon/proprietary/lib/libsensor_yamaha_test.so:system/lib/libsensor_yamaha_test.so


## RIL (Radio Interface Relay)
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/trebon/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/trebon/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/trebon/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so

## Camera
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/samsung/trebon/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/trebon/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/trebon/proprietary/lib/libcaps.so:system/lib/libcaps.so \
    vendor/samsung/trebon/proprietary/lib/libseccamera.so:system/lib/libseccamera.so \
    vendor/samsung/trebon/proprietary/lib/libseccameraadaptor.so:system/lib/libseccameraadaptor.so\
    vendor/samsung/trebon/proprietary/lib/libs3cjpeg.so:system/lib/libs3cjpeg.so \
    vendor/samsung/trebon/proprietary/lib/libsecjpegencoder.so:system/lib/libsecjpegencoder.so\
    vendor/samsung/trebon/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/trebon/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/trebon/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/trebon/proprietary/lib/libPanoraMax1.so:system/lib/libPanoraMax1.so \
    vendor/samsung/trebon/proprietary/lib/libPlusMe.so:system/lib/libPlusMe.so \
    vendor/samsung/trebon/proprietary/lib/libActionShot.so:system/lib/libActionShot.so \
    vendor/samsung/trebon/proprietary/lib/libCaMotion.so:system/lib/libCaMotion.so \
    vendor/samsung/trebon/proprietary/lib/libPlusMe.so:system/lib/libPlusMe.so 
    
## FM
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/samsung/trebon/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/samsung/trebon/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/trebon/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/trebon/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/trebon/proprietary/lib/libdsutils.so:system/lib/libdsutils.so
    
## Media
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/samsung/trebon/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/trebon/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/trebon/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/samsung/trebon/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so\
    vendor/samsung/trebon/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/trebon/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/samsung/trebon/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so 
## Atheros firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/wifi/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
    vendor/samsung/trebon/proprietary/wifi/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/samsung/trebon/proprietary/wifi/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \

## Adreno 200 GPU
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/samsung/trebon/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/samsung/trebon/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/samsung/trebon/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/samsung/trebon/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/samsung/trebon/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/samsung/trebon/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/samsung/trebon/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so 

## GPU firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/samsung/trebon/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw

## Binaries
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/trebon/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init

## Other libs
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/trebon/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/samsung/trebon/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/samsung/trebon/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/samsung/trebon/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/samsung/trebon/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so

## OMX
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/samsung/trebon/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/samsung/trebon/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/samsung/trebon/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/samsung/trebon/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/samsung/trebon/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/samsung/trebon/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so

## Sensors
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/trebon/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so

## Camera
PRODUCT_COPY_FILES += \
    vendor/samsung/trebon/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so
